version: 2.1
orbs:
  node: circleci/node@5.0.1
  browser-tools: circleci/browser-tools@1.4.0

jobs:
  build:
    working_directory: ~/my-project
    docker:
      - image: cimg/node:16.10.0
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"      
    steps:
      - browser-tools/install-chromedriver
      - checkout
      - restore_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"

      - run:
          name: Lint
          command: npm run ng lint
      - run:
          name: Unit Test
          command: npm run ng test -- --watch=false --browsers=ChromeHeadless --code-coverage
          environment:
            CHROME_BIN: /usr/bin/google-chrome
      - run:
          name: Coveralls
          command: cat ./coverage/angular-hello-world/lcov.info  | ./node_modules/coveralls/bin/coveralls.js
